spring:
  application:
    name: payments

  datasource:
    driver-class-name: org.postgresql.Driver
    password: 123456Az
    username: postgres
    url: jdbc:postgresql://localhost:5432/billing_payments
  liquibase:
    enabled: false
    drop-first: false
    default-schema: public
    change-log: classpath:/db/changelog/db.changelog-master.yaml
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

server:
  port: 8084

rabbitmq:
  queue:
    name: payment_queue
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
    enabled: true